######################################################################
# WARNING: 'lib/Config_git.pl' is generated by make_patchnum.pl
#          DO NOT EDIT DIRECTLY - edit make_patchnum.pl instead
######################################################################
$Config::Git_Data=<<'ENDOFGIT';
git_commit_id='b62845c7186b0b6a8e4e83419e6b5ef64ceef3ed'
git_describe='v5.42.2'
git_branch='v5.42.2'
git_uncommitted_changes=''
git_commit_id_title='Snapshot of:'
git_commit_date='2026-03-29 11:54:01 +0100'
git_snapshot_date='2026-03-29 11:54:01 +0100'

ENDOFGIT
